Add NatSpec & preliminary Forge tests
ori-wagmi/DCTRLMEMBERSHIP pull request #2
Opened 2024-01-15 04:37 UTC by 5951-rg

2024-01-15 04:46 UTC, 5951-rg commented
To install Foundry, having `cargo` already:
`cargo install --git https://github.com/foundry-rs/foundry --profile local --locked forge cast chisel anvil`

To run tests (increase v's for verbosity):
`forge test -v`

2024-01-15 05:44 UTC, ori-wagmi requested changes

2024-01-15 05:44 UTC, ori-wagmi commented on foundry.toml
> +solc = "0.8.22"
I don't love that we have two solidity versions to maintain, here and in hardhat.config.js. 

Looking at this example, they don't have an explicit solc in foundry.toml: https://github.com/foundry-rs/HardhatInFoundry

It looks like you're using the hardhat-foundry library, can you see if this line is necessary?

2024-01-15 05:44 UTC, ori-wagmi commented on contracts/FobNFT.sol
> +/// @author Ori Wagmi (ori-wagmi)
Do you have any strongly held beliefs on natspec and comments in general?

I don't like having authors in code (which is ironic given [this](https://github.com/ori-wagmi/DCTRLMEMBERSHIP/blob/5611a1e708a84966d9663c8af9db40259a6ba29c/scripts/tool/start.js#L18C1-L19C1)). Maybe the difference is that this comment will likely be published on etherscan and enshrined forever on the internet, whereas the script is only run and seen locally.

I'm going to push back and say comments for the sake of comments is a waste of space and we should be conscious of where/when we use them. Let me know what you think tho :)

2024-01-15 05:44 UTC, ori-wagmi commented on contracts/FobNFT.sol
> +    // @var Map a token to ID to an expiration number.
nit: `tokenId` rather than `tokewn to Id`?

2024-01-15 05:44 UTC, ori-wagmi commented on contracts/FobNFT.sol
> +    /// @dev Grants admin role to passed address upon initialization.
nit: comment should call out that it also grants burner and minter role?

2024-01-15 05:44 UTC, ori-wagmi commented on contracts/FobNFT.sol
> +    /// @dev    Expiry as string, not protocol prefix as required for URI.
good callout on the non-standard behavior. I'm not sure if following ERC721 spec is necessary/appropriate or not. Feels like a PM decision haha

2024-01-15 05:44 UTC, ori-wagmi commented on contracts/FobNFT.sol
> +    /// @notice Mint a new token ID for m months.
is `m months` a typo? `m` is misleading since that isn't the name of the arg

2024-01-15 05:44 UTC, ori-wagmi commented on contracts/FobNFT.sol
> +    /// @notice Mint a new token ID for m months.
I would phrase it as: `Mint a new token ID for 'months'`

2024-01-15 05:44 UTC, ori-wagmi commented on contracts/FobNFT.sol
> +    /// @dev Must be an existing ID, adds 30 days to expiry. Minter role only.
`extends expiry in increments of 30 days`?

2024-01-15 05:44 UTC, ori-wagmi commented on contracts/FobNFT.sol
> +    /// @dev Must be an existing ID, adds 30 days to expiry. Minter role only.
Maybe something about assuming each month == 30 days

2024-01-15 05:44 UTC, ori-wagmi commented on contracts/FobNFT.sol
> +    /// @dev Internal mint function, add 30 days to current, emit mint event.
similar to above, it's not just 30 days, it's 30 days * `months`

2024-01-15 05:44 UTC, ori-wagmi commented on contracts/MembershipNFT.sol
> +    // @var Maps bytes to a token ID.
comments should explain that `bytes` is the namehash of the `name` field in the nftMetadata

2024-01-15 05:44 UTC, ori-wagmi commented on contracts/MembershipNFT.sol
>          totalSupply += 1; // tokenId starts at 1
we do something a bit different here.

normally both TokenId and TotalySupply are 0 indexed.

however, we are 1 indexing TokenId, that is, the first token minted is `TokenId==1` and `TokenId==0` is actually invalid. This is necessary because `nameToId` defaults to returning 0 for all names.

2024-01-15 05:44 UTC, ori-wagmi commented on contracts/MembershipNFT.sol
>          totalSupply += 1; // tokenId starts at 1
The @dev comment should be updated to reflect this

2024-01-15 05:44 UTC, ori-wagmi commented on contracts/MembershipNFT.sol
> +        // @todo check-effects-interactions
what is this?

2024-01-15 05:44 UTC, ori-wagmi commented on contracts/MembershipNFT.sol
> +    /// @dev MINTER_ROLE and TRANSFER_ROLE are set in constructor
The reason i call out "manually managed" is that if `multisig_A` transfers Admin to `multisig_B`, it needs to explicitly revoke/grant admin roles.

2024-01-15 05:44 UTC, ori-wagmi commented on contracts/Minter.sol
> +/// @dev Minter can issue, reissue or extend.
nit: i prefer oxford comma :)

2024-01-15 05:44 UTC, ori-wagmi commented on contracts/Minter.sol
> +    /// @dev Cannot issue to Admin, no namehash collision.
I don't think there's anything stopping you from issuing to Admin?

2024-01-15 05:44 UTC, ori-wagmi commented on contracts/Minter.sol
> +    /// @dev Cannot issue to Admin, no namehash collision.
back when I had `issueMembership` and `issueMembershipCustodian` it was true, but i've since changed that requirement

2024-01-15 05:44 UTC, ori-wagmi commented on tests_forge/Minter.t.sol
> +        vm.createSelectFork(vm.envString("RPC_URL_MAINNET"));
This seems to be a new `.env` requirement, please update the `README.md` to allow anyone to setup and run the project

2024-01-15 05:44 UTC, ori-wagmi commented on tests_forge/Minter.t.sol
> +        registry = 0x000000006551c19487814612e58FE06813775758;
hmm, you're assuming we use the existing Registry/AccountV3 deployments.

I'm not entirely sure that's appropriate, for a couple reasons:
1. [low pri] Not sure if deployments exist on all chains including testnet.
2. [med pri] I'm worried that in the future the local versions of these contracts may get out of sync with what's deployed, thus the test no longer reflects the tool?
3. [med pri] this requires tests to be run on Mainnet Fork. Ideally tests can be run on local hardhat fork?

2024-01-15 05:44 UTC, ori-wagmi commented on tests_forge/Minter.t.sol
> +        alanah = vm.addr(3);
interesting choices on user names haha

2024-01-15 05:44 UTC, ori-wagmi commented on tests_forge/Minter.t.sol
> +    function testAccountsRoles() public view {
You're not really testing if all you do is console.log, right? xD

2024-01-15 05:44 UTC, ori-wagmi commented on tests_forge/Minter.t.sol
> +    function testAccountsRoles() public view {
consider renaming to just `printAccountRoles`

2024-01-15 05:44 UTC, ori-wagmi commented on tests_forge/Minter.t.sol
> +        console.log("ID 1 Name: ", metaName );
should assert `metaName == keccak256(abi.encode(memberName))` and `createDate == block.timestamp`

2024-01-15 05:44 UTC, ori-wagmi commented on tests_forge/Minter.t.sol
> +        //@todo Does frontend handle selecting fob tokenID (fobNumber)?
Yes, expected frontend to handle it since we never want the real tokenId to be publically available

2024-01-15 05:44 UTC, ori-wagmi commented on tests_forge/Minter.t.sol
> +        registry = 0x000000006551c19487814612e58FE06813775758;
4. [high pri] per line 271, you assume Eth L1 Mainnet. We are most likely going to deploy this to Optimism, so by explicitly assuming EthL1&&chainId, the test is no longer reflective of reality

2024-01-15 05:44 UTC, ori-wagmi commented on tests_forge/Minter.t.sol
> +        assertNotEq(expiry, 0);
should assert expirity == block.timstamp+12 months.

2024-01-15 05:44 UTC, ori-wagmi commented on tests_forge/Minter.t.sol
> +        assertGt(fob.idToExpiration(1), expiry + 12);
you should assert `fob.expirty == expiry+12+6 months`

2024-01-15 05:44 UTC, ori-wagmi commented on tests_forge/Minter.t.sol
> +        // @todo But shouldn't this account for existing expiry credit?
Interesting thought. I think i intended `reissue` to mean "This fob no longer belongs to person A and i'm going to give it to a completely new Person B"

The scenarios are like... a lost&found fob or someone moving away from vancouver.  In which case, i think resetting the expiry rather than rolling it along is appropriate.

2024-01-15 05:44 UTC, ori-wagmi commented on tests_forge/Minter.t.sol
> +        // Elapse time ~one block til expiry
Just curious, why do you do 12 seconds on line 205 and 13 seconds here?

2024-01-15 07:01 UTC, 5951-rg commented on foundry.toml
> +solc = "0.8.22"
Probably not necessary. Was specifying on workstation to resolve local issue.

2024-01-15 07:05 UTC, 5951-rg commented on contracts/FobNFT.sol
> +/// @author Ori Wagmi (ori-wagmi)
NatSpec is recommended for tooling like generating docs, plus user hints in the dApp.
Author is definitely optional. My default is to attribution :)

Overall, I think these are important for future people that pick this up.

Any stray comments outside of tags are just me taking notes and can remove to reduce clutter.

2024-01-15 07:05 UTC, 5951-rg commented on contracts/FobNFT.sol
> +    // @var Map a token to ID to an expiration number.
Yup typo!

2024-01-15 07:06 UTC, 5951-rg commented on contracts/FobNFT.sol
> +    /// @dev Grants admin role to passed address upon initialization.
Indeed - missed that in refactor.

2024-01-15 07:07 UTC, 5951-rg commented on contracts/FobNFT.sol
> +    /// @notice Mint a new token ID for m months.
Agreed.

2024-01-15 07:10 UTC, 5951-rg commented on contracts/FobNFT.sol
> +    /// @dev    Expiry as string, not protocol prefix as required for URI.
Should return something other apps will render, even if just HTML.
Agreed on needing decision there.

2024-01-15 07:12 UTC, 5951-rg commented on contracts/MembershipNFT.sol
>          totalSupply += 1; // tokenId starts at 1
Will update.

2024-01-15 07:13 UTC, 5951-rg commented on contracts/MembershipNFT.sol
> +        // @todo check-effects-interactions
Stray note for me.

2024-01-15 07:31 UTC, 5951-rg commented on contracts/Minter.sol
> +    /// @dev Cannot issue to Admin, no namehash collision.
Correct, carried over from earlier version. Will amend.

2024-01-15 07:36 UTC, 5951-rg commented on tests_forge/Minter.t.sol
> +        registry = 0x000000006551c19487814612e58FE06813775758;
Agreed, definitely better to use values closer to target.
This should run right now on local Anvil fork of mainnet at current block.
But can add deployment of custom registry to test setUp as we get closer to a deployment script.

2024-01-15 07:39 UTC, 5951-rg commented on tests_forge/Minter.t.sol
> +        alanah = vm.addr(3);
Authors of ERC6551 with A, B names :grin:

2024-01-15 07:43 UTC, 5951-rg commented on tests_forge/Minter.t.sol
> +        // @todo But shouldn't this account for existing expiry credit?
Ah makes sense.  UI should make it clear.

2024-01-15 07:43 UTC, 5951-rg commented on tests_forge/Minter.t.sol
> +        // Elapse time ~one block til expiry
Typo.

2024-01-15 08:41 UTC, 5951-rg commented on tests_forge/Minter.t.sol
> +        registry = 0x000000006551c19487814612e58FE06813775758;
Re 1, 2 and for reference: https://docs.tokenbound.org/contracts/deployments.
Registry is immutable and would expect to just have to modify test if otherwise.

2024-01-15 08:50 UTC, 5951-rg commented on tests_forge/Minter.t.sol
> +    function testAccountsRoles() public view {
Forge requires 'test' prepended to name to be callable. 
Compromise: move below actual tests and set visibility to `internal`

2024-01-15 09:01 UTC, 5951-rg commented on tests_forge/Minter.t.sol
> +        console.log("ID 1 Name: ", metaName );
`metaName` needs also to be hashed but yes worth covering.

2024-01-19 19:38 UTC, ori-wagmi approved these changes

2024-01-19 19:38 UTC, ori-wagmi commented on tests_forge/Minter.t.sol
> +            1, // chainId,
put chainId in .env since RPC_NODE_URL may not be eth L1

2024-01-24 01:30 UTC, closed without merging